### ISSUE TITLE
Buffer is read-only: #<buffer *Messages*> when using non-async version

### ISSUE THREAD

**Issue by garyo** [bwachter/system-environment#2]
I get the above error whenever I try to use the non-async version, which makes sense since in recent Emacs versions "*Messages*" and "*Warnings*" are read-only. I changed the `shell-command` stderr buffer to "*environment-import-stderr*" and that seems to fix it. (You'll only notice this if your shell command prints something on stderr.)

**Comment by bwachter** [comment]
Yes, you are correct that I shouldn't have set this to the *Messages* buffer. Seems the read only change to the *Messages* buffer got introduced in 24.4 - and in retrospect explains the very rare error I received now and then after upgrading to that version.

**Comment by bwachter** [comment]
Fixed in db7c883afe82d2a93711c5229ea9982298fda1ad
